### ISSUE TITLE
IE Edge identified as Chrome

### ISSUE THREAD

**Issue by korys** [ua-parser/uap-php#40]
Folling user agent:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240 

is incorrectly identified as Chrome. Should be identified as Edge.

**Comment by ThaDafinser** [comment]
@korys it's detected correctly as Edge
(maybe your version is outdated?)
http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F42.0.2311.135+Safari%2F537.36+Edge%2F12.10240

**Comment by korys** [comment]
I've tested here: http://uaparser.dmolsen.com/

Result:

ua->family: Chrome
  ua->major: 42
  ua->minor: 0
  ua->patch: 2311
  ua->toString: Chrome 42.0.2311
  ua->toVersionString: 42.0.2311
  os->family: Windows
  os->major: 
  os->minor: 
  os->patch: 
  os->patch_minor: 
  os->toString: Windows
  os->toVersionString: 
  device->family: Other
  toFullString: Chrome 42.0.2311/Windows
  uaOriginal: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by psicinski** [comment]
hi according to @korys  there is also issue with remaining OS system detection : Java ME, Symbian, iOS, Macintosh
as for browsers that are appearing as Other due to browser type provided the list is added here:
firefox 51, Microsoft edge 14, firefox 50 , firefox 40 Microsoft Edge 13 firefox 52, firefox 47, firefox 45, firefox 48, firefox 8 , firefox 49, Microsoft Edge 12

i also used @korys  method to get needed for above Os / Browsers data and all of ua->family , os->family are recognized as Other

**Comment by ThaDafinser** [comment]
@korys your test tool don't show any version used, So this may be outdated?

**Comment by korys** [comment]
@ThaDafinser It's not my test tool. It is pointed in the documentation: https://github.com/ua-parser/uap-php#demo. Is the documentation outdated?

**Comment by bvisness** [comment]
@korys It appears that the dmolsen test page is probably out of date. I just pulled the latest version of the library for myself and Edge identifies correctly as Edge. In the same browser, dmolsen's page identifies Edge as Chrome.

**Comment by lstrojny** [comment]
Closing
