### ISSUE TITLE
tag sf4 support please

### ISSUE THREAD

**Issue by cordoval** [ua-parser/uap-php#46]
i need a tag in order for this Pr to work https://github.com/nelmio/NelmioSecurityBundle/pull/165

**Comment by joubertredrat** [comment]
I have same issue here.

**Comment by kariae** [comment]
bump :)

**Comment by sdufel** [comment]
bump

**Comment by BallisticPain** [comment]
@cordoval Is this something you could provide a PR for? Or does it just need the actual "release tag"?

**Comment by cordoval** [comment]
@BallisticPain just tag, because is locking the other library nelmio bundle

**Comment by cordoval** [comment]
can those thumbs down explain why you guys are voting against? just curious

**Comment by jamiestraw** [comment]
@cordoval there aren't any thumbs-downs against this issue.

Only the "me too", "bump" or "+1" comments have been down-voted because it's annoying to constantly receive pointless emails - this is why the react feature exists.

There's only 2 of these comments now, but there was 3 of them - it's irritating.

**Comment by lstrojny** [comment]
v3.5.0 has been tagged
